version: "3.7"

services:
  # indexer:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - db
  #     - hasura
  #   restart: always

  db:
    image: postgres
    ports:
      - 0.0.0.0:5432:5432
    restart: always
    volumes:
      - db:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dipdup"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=dipdup
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=dipdup

  hasura:
    image: hasura/graphql-engine
    ports:
      - 0.0.0.0:42000:8080
    depends_on:
      - db
    restart: always
    environment:
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_DATABASE_URL=postgres://dipdup:postgres_password@db:5432/dipdup
      - HASURA_GRAPHQL_ADMIN_SECRET=admin_password
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=user

volumes:
  db:
