# generated by datamodel-codegen:
#   filename:  create_offer.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CreateOfferParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    amount: str
    duration: str
    interest: str
    listing_id: str
