# generated by datamodel-codegen:
#   filename:  mint.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class Attribute(BaseModel):
    class Config:
        extra = Extra.forbid

    category: str
    ints: Dict[str, str]
    sets: Dict[str, List[str]]
    strings: Dict[str, str]


class MintParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    attribute: Attribute
    editions: str
    metadata: Dict[str, str]
