# generated by datamodel-codegen:
#   filename:  update_attributes.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class UpdateAttributesParameterItem(BaseModel):
    class Config:
        extra = Extra.forbid

    ints: Dict[str, str]
    sets: Dict[str, List[str]]
    strings: Dict[str, str]
    token_id: str


class UpdateAttributesParameter(BaseModel):
    __root__: List[UpdateAttributesParameterItem]
